name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RICH_DISABLE_PROGRESS: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python install pytest

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install project
        run:
          pytest -v